---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-kafka-nodeport
spec:
  type: NodePort 
  selector:
    component: zookeeper
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181
    nodePort: 30005

