---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nifi-deployment
    labels:
      run: nifi
spec:
  selector:
    matchLabels:
      run: nifi
  replicas: 1
  template: 
    metadata:
      name: nifi
      labels:
        run: nifi
    spec:
      containers:
        - name: nifi
          image: apache/nifi
          ports:
          - containerPort: 8080
            protocol: TCP

