---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nifi
  name: nifi-service
spec:
  ports:
  - nodePort: 30006
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: nifi
  type: NodePort
