---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      component: kafka
  template:
    metadata:
      labels:
        component: kafka
    spec:
      containers:
      - name: kafka
        image: pharosproduction/kafka_k8s:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 9092
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper-service-kafka:2181
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: $(POD_IP)
        tty: true
      #   livenessProbe:
      #     exec:
      #       command:
      #         - /opt/check.sh
      #     initialDelaySeconds: 30
      #     periodSeconds: 30
      #   readinessProbe:
      #     exec:
      #       command:
      #         - /opt/check.sh
      #     initialDelaySeconds: 30
      #     periodSeconds: 5
      #   command:
      #     - /bin/bash
      imagePullSecrets:
        - name: regcred
      
