---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort 
  selector:
    component: kafka
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    nodePort: 30007

