---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service-kafka
spec:
  type: ClusterIP 
  selector:
    component: zookeeper
  ports:
  - name: zookeeper
    port: 2181
    targetPort: 2181

